
build:
  version: "3.0"

accounts:
  message: "Welcome to StedFast accounts APIs"
  contactDetails:
    name: "Jisageo"
    email: "jisageorge@stedfast.com"
  onCallSupport:
    -(111) 222-333
    -(111) 222-555